FROM postgres:16

RUN mkdir -p /var/lib/postgresql/certs

COPY ./certs/server.crt /var/lib/postgresql/certs/server.crt
COPY ./certs/server.key /var/lib/postgresql/certs/server.key

RUN chown 999:999 /var/lib/postgresql/certs/server.key \
    && chmod 600 /var/lib/postgresql/certs/server.key